### PR TITLE
Adding Android project type, updating README to include rails/grails

### PR DESCRIPTION
**Pull request by KyleBanks**

### CODE REVIEW

**Comment by KyleBanks** [comment]
P.S. Sweet app, very useful.

**Comment by teammixture** [comment]
Can you confirm these all work ok for a few different projects please as I don't have ones to test with
Thanks
Pete

**Comment by KyleBanks** [comment]
Works with plenty of my Grails/Android projects

screen shot 2013-12-11 at 3 31 37 pm

**Comment by KyleBanks** [comment]
Sorry just noticed something wrong. I saw the rails.png file and assumed the JSON was there to support it, but it wasn't on README so I added it. Turns out it's not defined in the JSON and isn't supported. I'll remove that.

**Pull request merged**
